### PR TITLE
Breakpoints

### PR DESCRIPTION
**Pull request by alimpfard**
Seeing as this is just about the most recent feature-complete simulator,
For the sake of the poor souls that have to use this to do actual simulations:
+ Added breakpoints
+ Set "Step" to step through instructions, not microoperations
+ Added "Skips" to automatically skip through ranges or instructions while stepping

### CODE REVIEW

**Comment by TomerAberbach** [comment]
Thank you for making a pull request! I'm pretty busy this week, but I think I'll have time next week to review your pull request and maybe give you some feedback. Thanks again for contributing!

**Comment by TomerAberbach** [comment]
Sorry that I never ended up following up on this. I think that the functionality you added is super cool and I hope you had fun implementing it!

With that said, I think I prefer leaving the simulator in its current state. It is currently used for the computer architecture class at The College of New Jersey and I think students benefit from having to step through all of the microoperations. For "real" programming I think breakpoints and hiding of smaller computations are very useful, but for an educational simulator of a toy computer I think those features make it easier for students to avoid understanding what's really happening under the hood.

I'm going to close this pull request, but feel free to reopen it if you have a good counterargument! 😃

**Comment by alimpfard** [comment]
Curiously enough, I ended up implementing these because debugging some code I wrote for the computer architecture class (not in the college of New Jersey :P) proved to be too annoying while stepping microop at a time.
I do understand your point though, so this PR is best closed.

**Comment by TomerAberbach** [comment]
Wow! Well, I don't think you would have been able to implement this without having a deep understanding of what's going on under the hood so your usage was clearly well-earned 😄

Out of curiosity, was your teacher having the entire class use this simulator for the course or did you just happen to find it online yourself?  And if your don't mind me asking, what school was it?

**Comment by alimpfard** [comment]
Nah, I just found it online.
Not many other result on Google for it lol
was University of Tabriz, Iran.

**Pull request closed without merging**
